version: '3.8'

services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=zackozack
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=devlinks
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:


  # devlinks-postgres-1